#+SETUPFILE: ~/git/org-html-themes/setup/theme-readtheorg.setup
#+OPTIONS: ^:nil
#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+TITLE: ROSS Data Processing
#+AUTHOR: Dylan Winters

* TODO Overview
This set of matlab functions is designed to process ADCP data
collected using ROSS kayaks with minimal code modifications between
trips and deployments. Each set of deployments requires a trip name,
consistent file & folder organization, and the creation of a
deployment file.

** File/Folder Structure
** Deployment Files
** Output Data
** Output Figures

* Data Sets

** 2016 Aug - LeConte Glacier
[[org/leconte_2016_aug.org][Processing log & figures]]

** TODO 2016 Nov - Palau
** TODO 2017 Jan - Newport
** TODO 2017 Jan - Puget Sound

[Summary figure]
[Surface velocity figure]

The two above figures show a bias in measured currents proportional to
ROSS's velocity. As ROSS travels clockwise along its four primary
transect directions, the currents appear to match the direction of
travel.

I grouped the data by transect direciton in case there was a
directional aspect to these problems. The colored points in the
figures below represent data where ROSS was moving faster than 2m/s
along one of these directions, and the black points show all other
data.

Plotting currents vs. ROSS's velocity from GPS measurements shows that
final corrected currents have a component that scales linearly with
ROSS's velocity (red dashed lines, upper 2 panels). This is indicative
of measured currents that are weaker than ROSS's velocity.

Measured currents in the forward-backward and port-starboard
directions scale normally with velocity when ROSS is moving slower
than 2m/s (black points; the green dashed line shows how measured
currents would scale with velocity in still water). When ROSS is
moving faster than 2m/s, forward-backward velocity is significantly
lower than expected, while port-starboard velocity is slightly higher
than expected.

These signs point towards some kind of instrument orientation
problem. However, bottom-track velocities would then experience
similar problems, which is not the case here. Bottom-track velocities
agree very closely with GPS velocities whenever the botton is in rage,
even at high speeds. Estimates of ROSS's speed using velocity data from
pings that hit the bottom are generally lower than GPS and BT speed:

[bottom track figure]

In summary:

- Measured velocities in the forward-backward direction are smaller
  than expected. This caused currents to be over-corrected when ship
  speed is removed, resulting in biases proportional to ship velocity.
- This is not due to incorrect instrument orientation, otherwise
  bottom-track velocities would be similarly incorrect.
- Velocity measurements from pings that hit the bottom are generally
  smaller than velocity measurements from BT and GPS.



** 2017 Apr - Petersburg

[[org/petersburg_2016_apr.org][Processing log & figures]]

- [[file:Code/petersburg_2017_apr/][Code]]
  - [[file:Code/petersburg_2017_apr/petersburg_2017_apr_swankie.m][Swankie]]
  - [[file:Code/petersburg_2017_apr/petersburg_2017_apr_rosie.m][Rosie]]
  - [[file:Code/petersburg_2017_apr/petersburg_2017_apr_casey.m][Casey]]

- [[file:Figures/petersburg_2017_apr][Figures]]
  - [[file:Figures/petersburg_2017_apr/Swankie][Swankie]]
  - [[file:Figures/petersburg_2017_apr/Rosie][Rosie]]
  - [[file:Figures/petersburg_2017_apr/Casey][Casey]]

- [[file:Data/petersburg_2017_apr/][Data]]
  - [[file:Data/petersburg_2017_apr/Swankie/][Swankie]]
  - [[file:Data/petersburg_2017_apr/Rosie/][Rosie]]
  - [[file:Data/petersburg_2017_apr/Casey/][Casey]]


*** ROSS Notes
#+name:kayak_info
| Name    | ADCP           | Flag   | Network |
|---------+----------------+--------+---------|
| Swankie | Sentinel V 300 | Sweden | ROSS6   |
| Rosie   | PAVS 150       | Alaska | ROSS3   |
| Casey   | Workhorse 600  | Norway |         |

*** Sentinel V Notes
Two-profiles
- 4m bins long-range profile mode
- 1m-2m high-resolution mode


| Profile         | Bins | Bin Size (m) | Bin 1 Distance (m) |
|-----------------+------+--------------+--------------------|
| Long Range      |   40 |          4.0 |               5.91 |
| High Resolution |   63 |          1.5 |               3.50 |




We did some testing from the drive-down dock in Petersburg
