#+SETUPFILE: ~/git/org-html-themes/setup/theme-readtheorg.setup
#+OPTIONS: ^:nil
#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+TITLE: ROSS Data Processing
#+AUTHOR: Dylan Winters

* TODO Overview
This repository is designed to serve as both a code repository and lab
notebook for processing data from Robotic Oceanographic Surface
Sampler (ROSS) kayaks. 

** File/Folder Structure
[[./Code][Code]], data, and [[./Figures][figures]] are organized by trips > kayaks >
deployments. Each trip has been given a unique name that is used for
organization.

** Deployment Files
Each trip requires a deployment file that contains processing
instructions for each kayak deployment.

See [[./Code/petersburg_2017_apr/petersburg_2017_apr_deployments.m][petersburg_2017_apr_deployments.m]] for an example deployment
file. Note that for this trip, deployment information has been
separated into different functions for each kayak: [[Code/petersburg_2017_apr/petersburg_2017_apr_rosie.m][Rosie]], [[Code/petersburg_2017_apr/petersburg_2017_apr_casey.m][Casey]], and
[[Code/petersburg_2017_apr/petersburg_2017_apr_swankie.m][Swankie]].

* Data Sets

** 2016 Aug - LeConte Glacier
- [[org/leconte_2016_aug_rosie.org][Rosie processing log & figures]]
- [[org/leconte_2016_aug_casey.org][Casey processing log & figures]]

** TODO 2016 Nov - Palau
** TODO 2017 Jan - Newport
** 2017 Jan - Puget Sound
- [[org/puget_2017_jan_spanky.org][Spanky processing log & figures]]
- [[org/puget_2017_jan.org][Additional notes]]


** 2017 Apr - Petersburg
- [[org/petersburg_2017_apr_rosie.org][Rosie processing log & figures]]
- [[org/petersburg_2017_apr_swankie.org][Swankie processing log & figures]]
- [[org/petersburg_2017_apr.org][Additional notes]]

